### ISSUE TITLE
Access control by question id 

### ISSUE THREAD

**Issue by Siqlain** [AMPATH/ngx-openmrs-formentry#2]
I am trying to understand the fuctionality of form entry.
Can any one here tell me if there is method to get  a control by question id

**Comment by Siqlain** [comment]
form.searchQuestionById

**Comment by Fatmali** [comment]
Hi Siqlain, yes there is have a look at [FormSchemaCompiler](https://github.com/AMPATH/ngx-openmrs-formentry/blob/ed880543c74bc8599d8d23955b2f2326f5d2e61a/projects/ngx-formentry/src/form-entry/services/form-schema-compiler.service.ts) line 63.
